version: "3.9"
services:
  issuer-database:
    container_name: "issuer-database"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    restart: "always"
    volumes:
      - "issuer-database:/data/db"
  edv.entity.id:
    container_name: "edv.entity.id"
    image: "ghcr.io/hypersign-protocol/hypersign-data-vault-service:latest"
    environment:
      PORT: 3000
      HOST: "edv.entity.id:3000"
      SSL: false
      ABSOLUTE_URL: "edv.entity.id:3000"
      DATA_VAULT: "./.encData"
      DB_URL: "mongodb://issuer-database:27017"
    depends_on:
      - "issuer-database"
  api.entity.id:
    container_name: "api.entity.id"
    image: "ghcr.io/hypersign-protocol/studio-api:latest"
    environment:
      PORT: 3001
      ENTITY_API_SERVICE_BASE_URL: "http://localhost:8080/"
      DATABASE_CONNECTION_PATH: "mongodb://issuer-database:27017/api?retryWrites=true&w=majority"
      BASE_DB_PATH: "mongodb://issuer-database:27017"
      HID_NETWORK_RPC: "https://rpc.jagrat.hypersign.id/"
      HID_NETWORK_API: "https://api.jagrat.hypersign.id/"
      HID_NETWORK_NAMESPACE: "testnet"
      EDV_BASE_URL: "http://edv.entity.id:3000/"
      EDV_CONFIG_DIR: ".api-edv-config"
      EDV_DID_FILE_PATH: ".api-edv-config/edv-did.json"
      EDV_KEY_FILE_PATH: ".api-edv-config/edv-keys.json"
      MNEMONIC: "parade erase firm goose old elegant sausage sweet stuff view goddess total museum hidden worry usual rug foster uncover cradle govern swing muscle unable"
      JWT_SECRET: "43bf9ba55e72565c35a2cd5ac52792ca965cb806be2027c5d83bd11ab826aaf250c8bcedc851cf54b059fbe800daeb02f801c395f306bc42a6f28be15b94e0ed"
      WHITELISTED_CORS: "[\"http://localhost:9001\",\"https://entity.hypersign.id\",\"http://localhost:3001\",\"https://api.entity.hypersign.id\"]"
      STUDIO_SERVER_JWT_SECRET: "caXHr6Xhz3teM2S75HmgNzjgpp7EHnrFyga6jWgyjpgSvqKCv1"
      SUPER_ADMIN_USERNAME: "root"
      SUPER_ADMIN_PASSWORD: "root"
      SESSION_SECRET_KEY: "43bf9ba55e72565d"
    depends_on:
      - "issuer-database"
      - "edv.entity.id"
  web:
    container_name: "nginx"
    image: "nginx:latest"
    ports:
      - "8080:8080"
    depends_on:
      - "api.entity.id"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
volumes:
  issuer-database: {}
